DATAS SEGMENT
    OLDS DB 100 DUP('$')  
    NEWS DB 100 DUP('$')  
    PROMPT1 DB 'Enter "OLDS" string: $'
    PROMPT2 DB 0DH, 0AH, 'Enter "NEWS" string: $'
    YES_MSG DB 0DH, 0AH, 'YES$'
    NO_MSG DB 0DH, 0AH, 'NO$'
DATAS ENDS

STACKS SEGMENT
    DB 100H DUP(0)  
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES, DS:DATAS, SS:STACKS
START:
    MOV AX, DATAS
    MOV DS, AX

    ; 读取第一个字符串
    MOV DX, OFFSET PROMPT1
    MOV AH, 09H
    INT 21H

    MOV DX, OFFSET OLDS
    MOV AH, 0AH
    INT 21H

    ; 读取第二个字符串
    MOV DX, OFFSET PROMPT2
    MOV AH, 09H
    INT 21H

    MOV DX, OFFSET NEWS
    MOV AH, 0AH
    INT 21H

    ; 比较字符串
    MOV SI, OFFSET OLDS
    ADD SI, 2  
    MOV DI, OFFSET NEWS
    ADD DI, 2  

COMPARE_STRINGS:
    MOV AL, [SI]
    CMP AL, [DI]
    JNE STRINGS_DIFFERENT
    CMP AL, 0DH  
    JE STRINGS_EQUAL
    INC SI
    INC DI
    JMP COMPARE_STRINGS

STRINGS_EQUAL:
    MOV DX, OFFSET YES_MSG
    JMP DISPLAY_RESULT

STRINGS_DIFFERENT:
    MOV DX, OFFSET NO_MSG

DISPLAY_RESULT:
    MOV AH, 09H
    INT 21H

    MOV AH, 4CH  
    INT 21H

CODES ENDS
END START


